name: iOS IPA (AltStore)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive

      - name: Workaround git safe.directory for submodules
        run: |
          git config --global --add safe.directory '*'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build unsigned IPA
        run: |
          flutter build ipa --release --no-codesign

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: reins-mcp-ipa
          path: build/ios/ipa/*.ipa